GeoNote/GeoNote/Controllers/HomeController.cs
namespace GeoNote.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using Microsoft.FSharp.Core;
    using Microsoft.FSharp.Collections;
    using PagedList;
    using GeoNote.DataAccess;
    using GeoNote.Models;
    using System.Web.Http.Cors;

    public class HomeController : Controller
    {
        [EnableCors(origins: "*", headers: "*", methods: "*")]
        public ActionResult Index()
        {
            Response.AppendHeader("Access-Control-Allow-Origin", "*");
            return View();
        }

        public ActionResult mobile()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "What is GeoNote?";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "GeoNote Contact.";

            return View();
        }
    }
}

GeoNote/GeoNote/Controllers/ImageController.cs
namespace GeoNote.Controllers
{
    using GeoNote.DataAccess;
    using GeoNote.Models;
    using PagedList;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Http.Cors;
    using System.Web.Mvc;

    public class ImageController : Controller
    {
        //
        // GET: /Image/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Images(int? page = null)
        {
            int pageNumber = (page ?? 1);

            DataAccessor accesss = new DataAccessor();
            List<Image> images = new List<Image>();
            images = accesss.GetImages();

            IPagedList<Image> imgs = null;

            if (images != null)
            {
                imgs = images.ToPagedList(pageNumber, 30);
            }

            return View(imgs);
        }

        public ActionResult UpdateNotes(Image img)
        {

            return RedirectToAction("Images");
        }

        [EnableCors(origins: "*", headers: "*", methods: "*")]
        public ActionResult SaveImage(Image img)
        {
            DataAccessor access = new DataAccessor();
            Image image = img;

            access.SaveImage(image);

            return RedirectToAction("Images");
        }
	}
}

GeoNote/GeoNote/Controllers/MapController.cs
using GeoNote.DataAccess;
using GeoNote.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GeoNote.Controllers
{
    public class MapController : Controller
    {
        //
        // GET: /Map/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Maps()
        {
            DataAccessor accesss = new DataAccessor();
            List<Image> images = new List<Image>();
            images = accesss.GetImages();

            return View(images);
        }
    }
}

GeoNote/GeoNote/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>GeoNote is a product full of endless possibilities.</p>
<p>Not only for Genscape's resources, but for humanitarian and recreational needs around the world!</p>

GeoNote/GeoNote/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    445 East Market St, Ste 200<br />
    Louisville, Ky 40202<br />
    <abbr title="Phone">P:</abbr>
    502.555.1337
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@GeoNote.com">Support@GeoNote.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@GeoNote.com">Marketing@GeoNote.com</a>
</address>

GeoNote/GeoNote/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <img src="~/Images/GeoNote400.png" />
    <p class="lead">Welcome to GeoNote! Within lies the photographs and data that you have taken! You can add details and use some fancy GIS tools (Google Maps)</p>
    <p class="lead">to even move something if for some unheard of reason computers and satellites and 1980s Russian Technology has failed you (or us).</p>
    <p><a href="http://www.genscape.com" class="btn btn-primary btn-large">Learn more &raquo;....ABOUT GENSCAPE!</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Images</h2>
        <p>
            Below you can head to your images page that has all your fancy images (Read: Poorly framed, poorly lit, blurry cat pictures)!
        </p>
        <p><a href="@Url.Action("Images", "Image", new { })">Images &gt;</a></p>
    </div>
    <div class="col-md-4">
        <h2>View Map!</h2>
        <p>We're mapping the places you took the photos, kind of like the NSA (Only we're the good guys?)!</p>
        <p><a href="@Url.Action("Maps", "Map", new { Images = Model })">Read More &gt;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Other Stuff:</h2>
        <p>In the future we're going to do some amazing things with this! We're looking at you bird watchers!</p>
        <p></p>
    </div>
</div>